export const typeOfMedia = [
    { value: "ANIME", name: "anime" },
    { value: "MANGA", name: "manga" },
];
export const animeTypes = [
    { value: undefined, name: "Any" },
    { value: "TV", name: "TV" },
    { value: "TV_SHORT", name: "TV Short" },
    { value: "MOVIE", name: "Movie" },
    { value: "SPECIAL", name: "Special" },
    { value: "OVA", name: "OVA" },
    { value: "ONA", name: "ONA" },
    { value: "MUSIC", name: "Music" },
];
export const mangaTypes = [
    { value: undefined, name: "Any" },
    { value: "MANGA", name: "manga" },
    { value: "NOVEL", name: "novel" },
    { value: "ONE_SHOT", name: "one shot" },
];
export const animeSortSettings = [
    { value: "ID", name: "ID" },
    { value: "TITLE_ROMAJI", name: "title" },
    { value: "TITLE_ROMAJI_DESC", name: "title descending" },
    { value: "START_DATE", name: "starting date" },
    { value: "START_DATE_DESC", name: "starting date descending" },
    { value: "SCORE", name: "score" },
    { value: "SCORE_DESC", name: "score descending" },
    { value: "POPULARITY", name: "popularity" },
    { value: "POPULARITY_DESC", name: "popularity descending" },
    { value: "TRENDING", name: "trending" },
    { value: "TRENDING_DESC", name: "trending descending" },
    { value: "EPISODES", name: "episodes" },
    { value: "EPISODES_DESC", name: "episodes descending" },
];
export const mangaSortSettings = [
    { value: "ID", name: "ID" },
    { value: "TITLE_ROMAJI", name: "title" },
    { value: "TITLE_ROMAJI_DESC", name: "title descending" },
    { value: "START_DATE", name: "starting date" },
    { value: "START_DATE_DESC", name: "starting date descending" },
    { value: "SCORE", name: "score" },
    { value: "SCORE_DESC", name: "score descending" },
    { value: "POPULARITY", name: "popularity" },
    { value: "POPULARITY_DESC", name: "popularity descending" },
    { value: "TRENDING", name: "trending" },
    { value: "TRENDING_DESC", name: "trending descending" },
    { value: "VOLUMES", name: "volumes" },
    { value: "VOLUMES_DESC", name: "volumes descending" },
    { value: "CHAPTERS", name: "chapters" },
    { value: "CHAPTERS_DESC", name: "chapters descending" },
];
export const seasons = [
    { value: undefined, name: "Any" },
    { value: "WINTER", name: "Winter" },
    { value: "SPRING", name: "Spring" },
    { value: "SUMMER", name: "Summer" },
    { value: "FALL", name: "Fall" },
];
export const genres = [
    { value: undefined, name: "Any" },
    { value: "Action", name: "Action" },
    { value: "Adventure", name: "Adventure" },
    { value: "Comedy", name: "Comedy" },
    { value: "Drama", name: "Drama" },
    { value: "Fantasy", name: "Fantasy" },
    { value: "Horror", name: "Horror" },
    { value: "Mahou Shoujo", name: "Mahou Shoujo" },
    { value: "Mecha", name: "Mecha" },
    { value: "Music", name: "Music" },
    { value: "Mystery", name: "Mystery" },
    { value: "Psychological", name: "Psychological" },
    { value: "Romance", name: "Romance" },
    { value: "Sci-Fi", name: "Sci-Fi" },
    { value: "Slice of Life", name: "Slice of Life" },
    { value: "Sports", name: "Sports" },
    { value: "Supernatural", name: "Supernatural" },
    { value: "Thriller", name: "Thriller" },
];
